<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="117106" started-at="2019-07-25T06:55:08Z" finished-at="2019-07-25T06:57:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="117106" started-at="2019-07-25T06:55:08Z" finished-at="2019-07-25T06:57:05Z">
      <class name="diTest.ByDesignTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:diTest.ByDesignTest@2b56f5f8]" name="setUp" is-config="true" duration-ms="6079" started-at="2019-07-25T13:55:08Z" finished-at="2019-07-25T13:55:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="createSalesOrderTest()[pri:0, instance:diTest.ByDesignTest@2b56f5f8]" name="createSalesOrderTest" duration-ms="111001" started-at="2019-07-25T13:55:14Z" finished-at="2019-07-25T13:57:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Values should be different. Actual: Save failed; refresh list to perform further actions]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Values should be different. Actual: Save failed; refresh list to perform further actions
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failEquals(Assert.java:185)
	at org.junit.Assert.assertNotEquals(Assert.java:161)
	at org.junit.Assert.assertNotEquals(Assert.java:175)
	at diPages.ByDesignPage.OutboundLogistics(ByDesignPage.java:348)
	at diTest.ByDesignTest.createSalesOrderTest(ByDesignTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSalesOrderTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:diTest.ByDesignTest@2b56f5f8]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-07-25T13:57:05Z" finished-at="2019-07-25T13:57:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- diTest.ByDesignTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
